log_level = "info"

data_path = "./db/"

# path to downloaded params folder
encoder_params_dir = "params/" 

# grpc server listen address
grpc_listen_address = "0.0.0.0:34001"
# chain eth rpc endpoint
eth_rpc_endpoint = "http://localhost:8545/"
# public grpc service socket address to register in DA contract
# ip:34001 (keep same port as the grpc listen address)
# or if you have dns, fill your dns
socket_address = "0g-da-node:34001"

# data availability contract to interact with
da_entrance_address = "0x9Ec76BC9364bbA2A06c5Db290A315b4ffd29d934"
# deployed block number of da entrance contract
start_block_number = 0

# signer BLS private key
signer_bls_private_key = "11"
validator_private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff8"
# signer eth account private key
signer_eth_private_key = "0x17939f5b4fa643ab86df3ae9d0b8f9c8c0c14328e679ece6c243d32dab673e49"
miner_eth_private_key = "0x9549f115b0a21e5071a8aec1b74ac093190e18dd83d019ac6497b0adfbeff26d"
# whether to enable data availability sampling
enable_das = "true"